package com.apnamart.apnarider.core_app_framework.logger.event

object EventKey {
    const val TIME_STAMP = "time_stamp"
    const val RIDER_LATITUDE = "rider_lat"
    const val RIDER_LONGITUDE = "rider_lng"
    const val GEOFENCE_LIST = "geofence_list"
    const val GEOFENCE_LONGITUDE = "geofence_lng"
    const val GEOFENCE_LATITUDE = "geofence_lat"
    const val GEOFENCE_TRANSITION = "geofence_transition"
    const val CUSTOMER_LATITUDE = "customer_lat"
    const val CUSTOMER_LONGITUDE = "customer_lng"
    const val STORE_NAME = "store_name"
    const val RECEIVER_NAME = "receiver_name"
    const val STORE_ID = "store_id"
    const val LOGOUT_DIALOG_ACTION = "logout_dialog_action"
    const val MARKED_OUT_REASON = "marked_out_reason"

    const val ORDER_NUMBER = "order_number"
    const val TIMER_TIME = "timer_time"
    const val MARK_IN_OR_OUT_TIME = "mark_in_or_out_time"
    const val ORDER_STATUS = "order_status"
    const val CALLED_CUSTOMER = "called_customer"
    const val CUSTOMER_DISTANCE = "customer_distance"
    const val STORE_DISTANCE_FROM_GEOFENCE_LOCATION = "store_distance_from_geofence_location"
    const val STORE_DISTANCE_FROM_CURRENT_LOCATION = "store_distance_from_current_location"
    const val BATTERY_OPTIMIZATION_PERMISSION = "battery_optimization_permission"
    const val OVERLAY_PERMISSION = "overlay_permission"
    const val ERROR_MESSAGE = "error_message"
    const val BILL_NO = "bill_no"
    const val ORDER_ID = "order_id"
    const val PAYMENT_MODE = "payment_mode"
    const val CITY = "city"
    const val CUSTOMER_NAME = "customer_name"
    const val CUSTOMER_PHONE = "customer_phone"
    const val AMOUNT = "amount"
    const val SOURCE = "source"
    const val AIRPLANE_MODE = "airplane_mode"
    const val INTERNET_AVAILABLE = "internet_available"
    const val REF_ID = "ref_id"

    //Signup-Login flow
    const val PHONE = "phone"
    const val APP_SIGNUP_PHONE_NUMBER_TYPE_STARTED = "app_signup_phone_number_type_started"
    const val PHONE_NUMBER_INPUT = "phone_number_input"
    const val OTP_VERIFY_TYPE = "otp_verify_type"
    const val HINT_SHOWN_SOURCE = "hint_shown_source"
    const val HINT_STATUS = "hint_status"
    const val OTP_SERVICE_PARTNER = "otp_service_partner"
    const val TOPIC = "topic"
    const val MESSAGE = "message"
    const val FINE_LOCATION_PERMISSION = "fine_location_permission"
    const val COARSE_LOCATION_PERMISSION = "coarse_location_permission"
    const val BACKGROUND_LOCATION_PERMISSION = "background_location_permission"
    const val CONNECTION_STATUS = "connection_status"
    const val SUBSCRIPTION_STATUS = "subscription_status"
    const val QR_TRANSACTION_ID = "qr_transaction_id"
    const val GEOFENCE_OBJECT = "geofence_object"

    //screen events
    const val SCREEN_NAME = "screen_name"
    const val TIME_SPENT = "time_spent"

    //updated profile events
    const val RIDER_UPDATED_NAME = "rider_updated_name"
    const val RIDER_OLD_NAME = "rider_old_name"
    const val RIDER_UPDATED_EMAIL = "rider_updated_email"
    const val RIDER_OLD_EMAIL = "rider_old_email"
}