name: Build Signed APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use the version compatible with your project
          distribution: 'temurin'

      # Decode and save the keystore file
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > app_keystore.jks

      # Build the signed APK
      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=app_keystore.jks \
                                     -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
                                     -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
                                     -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # Upload the signed APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Signed APK
          path: app/build/outputs/apk/release/*.apk
