name: Build and Sign APK

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use the version compatible with your project
          distribution: 'temurin'

      # Decode and save the keystore file
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > app_keystore.jks

      # Build the unsigned APK
      - name: Build Unsigned APK
        run: |
          ./gradlew assembleRelease

#      # Sign the APK
#      - name: Sign APK
#        env:
#          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#        run: |
#          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
#                    -keystore app_keystore.jks \
#                    -storepass $KEYSTORE_PASSWORD \
#                    -keypass $KEY_PASSWORD \
#                    app/build/outputs/apk/release/app-release-unsigned.apk \
#                    $KEY_ALIAS

      - name: Sign App
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
           releaseDir: app/build/outputs
           signingKey: ${{ secrets.KEYSTORE_FILE }}
           keyAlias: ${{ secrets.KEY_ALIAS }}
           keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
           keyPassword: ${{ secrets.KEY_PASSWORD }}


      # Align the APK
      - name: Align APK
        run: |
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk \
                    app/build/outputs/apk/release/app-release.apk

      # Upload the signed APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Signed APK
          path: app/build/outputs/apk/release/*.apk
