name: Build Signed APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends wget unzip
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
            mkdir -p $HOME/android-sdk/cmdline-tools
            unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
            mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "build-tools;34.0.0"

      # Step 3: Decode and save keystore
      - name: Decode and save keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks

      # Step 4: Build the APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Step 5: Sign the APK
      - name: Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          jarsigner -verbose -keystore keystore.jks \
            -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD \
            app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS

      # Step 6: Align the APK
      - name: Optimize APK
        run: |
          zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release.apk

      # Step 7: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/app-release.apk
