name: Build Compose App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Cache Gradle Wrapper
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      # Step 4: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      # Step 5: Build APK
      - name: Build APK
        run: |
          ./gradlew clean
          if [ "${{ github.ref_name }}" == "main" ]; then
            ./gradlew assembleRelease --no-daemon --stacktrace
          elif [ "${{ github.ref_name }}" == "uat" ]; then
            ./gradlew assembleDebug --no-daemon --stacktrace
          fi


      # Step 6: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}-apk
          path: app
